Made the client synchronous
reportportal/client-javascript pull request #13
Opened 2017-06-29 14:24 UTC by lexecon

2017-06-29 14:52 UTC, ksuglotova requested changes

2017-06-29 14:52 UTC, ksuglotova commented on README.md
> +Client to communicate with the Report Portal on node js.
This Client is to communicate

2017-06-29 14:52 UTC, ksuglotova commented on README.md
>  Library used only for implementors of custom listeners for ReportPortal.
Library is used

2017-06-29 14:52 UTC, ksuglotova commented on README.md
> +launch    | Name of lunch at creation.
Name of launch

2017-06-29 14:52 UTC, ksuglotova commented on README.md
> +project   | The name of the project in which the lunches will be created.
in which the launches

2017-06-29 14:52 UTC, ksuglotova commented on README.md
> +Each method (except checkConnect) returns an object of a specific format:
in a specific format?

2017-06-29 14:52 UTC, ksuglotova commented on README.md
> +The client works synchronously, so to send the following requests it is not necessary to wait for the end of previous ones.
so it is not necessary to wait for the end of the previous requests to send following ones.

2017-06-29 14:52 UTC, ksuglotova commented on README.md
> + checkConnect - asynchronous method for verifying the correct connection of the client
for verifying the correctness of the client connection?

2017-06-29 14:52 UTC, ksuglotova commented on README.md
> +startLaunch - starts a new launch, return temp id that you want to use for all items within this lunch.
returns temp id that you may use for all of the launches within this launch

2017-06-29 14:52 UTC, ksuglotova commented on README.md
> +name      | (optional) lunch name. Default: parameter 'launch' specified when creating the client instance
launch

2017-06-29 14:52 UTC, ksuglotova commented on README.md
> +tags      | (optional) array of launch tags
would it be useful to add tags separator in tags parameter description?

2017-06-29 14:52 UTC, ksuglotova commented on README.md
> +If you want to know the real id launch, wait for the method to finish (the real id does not participate in the client's work)
To know the real launch id wait for the method to finish (the real id is not used by the client)

2017-06-29 14:52 UTC, ksuglotova commented on README.md
> +The request to finish the lunch will be sent only after all items within it have finished.
launch

2017-06-29 14:52 UTC, ksuglotova commented on README.md
> +status    | (optional) status launch, one of "", "PASSED", "FAILED", "STOPPED", "SKIPPED", "RESTED", "CANCELLED". Default: "".
status of launch

2017-06-29 14:52 UTC, ksuglotova commented on README.md
> +* data object - can contain the following fields: description, tags, mode. These fields can be looked up in the method "startLaunch".
may contain

2017-06-29 14:52 UTC, ksuglotova commented on README.md
> +end_time  | (optional) end time of lunch. Default: rpClient.helpers.now()
launch

2017-06-29 14:52 UTC, ksuglotova commented on README.md
> +status    | (optional) status launch, one of "", "PASSED", "FAILED", "STOPPED", "SKIPPED", "RESTED", "CANCELLED". Default: "PASSED".
launch status

2017-06-29 14:52 UTC, ksuglotova commented on README.md
> +message   | (optional) message log. Default: ''.
log message

2017-06-29 14:52 UTC, ksuglotova commented on README.md
> +status    | (optional) status log, one of 'trace', 'debug', 'info', 'warn', 'error', ''. Default "".
log status

2017-06-29 15:51 UTC, Xotabu4 commented
Thanks for documentation!

2017-06-30 06:18 UTC, lexecon commented on README.md
> +startLaunch - starts a new launch, return temp id that you want to use for all items within this lunch.
for all *items*

2017-06-30 06:20 UTC, lexecon commented on README.md
> +tags      | (optional) array of launch tags
do not understand

2017-06-30 11:44 UTC, merged