GA4
reportportal/client-javascript pull request #154
Opened 2023-04-17 15:51 UTC by HardNorth

2023-04-21 17:04 UTC, AmsterGet requested changes

2023-04-21 17:04 UTC, AmsterGet commented on statistics/statistics.js
> +    if (agentParams && Object.hasOwn(agentParams, 'name') && agentParams.name) {
I suggest to use `targetObject.hasOwnProperty` instead as we declare the support of Node.js >=10.
`Object.hasOwn` supported only from [Node.js v16.9.0](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn#browser_compatibility).
I plan to drop support of stale Node.js versions together with migration to TS.

2023-04-21 17:04 UTC, AmsterGet commented on statistics/statistics.js
> +      client_id: getClientId(),
I see that this property generated once for the particular client.
Is it to identify unique clients?

2023-04-21 17:04 UTC, AmsterGet commented on statistics/clientId.js
> +// client-id.js
Please remove the comment if it is not required.

2023-04-21 17:04 UTC, AmsterGet commented on statistics/constants.js
> +}
I'm not sure if we need to check and detect the browser version as this client is only designed to run in a Node.js environment.
Any attempt to request anything from the file system or use the native Node.js API will fail in the browser for this library.
In case of Cypress that can run the tests directly in browser, the reporter lives separately in the Node.js process.

2023-04-26 08:22 UTC, HardNorth commented on statistics/statistics.js
> +      client_id: getClientId(),
Yes, by this ID we can see new / old users in statistics.

2023-04-26 08:22 UTC, HardNorth commented on statistics/statistics.js
> +    if (agentParams && Object.hasOwn(agentParams, 'name') && agentParams.name) {
Done

2023-04-26 08:22 UTC, HardNorth commented on statistics/clientId.js
> +// client-id.js
Done

2023-04-26 08:30 UTC, HardNorth commented on statistics/constants.js
> +}
OK, removed

2023-04-26 08:37 UTC, HardNorth commented
@AmsterGet I found I missed that `trackEvent` function is async, so I updated everything in `client-id.js` to be async. Also I renamed `clientId.js` to `client-id.js` to be more consistent with other JS file names.

2023-04-26 12:39 UTC, AmsterGet approved these changes

2023-04-26 12:39 UTC, merged