finish test item error case
reportportal/client-javascript pull request #19
Opened 2018-06-20 07:29 UTC by vadimromanyak

finish test item even if its children fail, this prevents step from
hanging in progress status and not being closed. 
when sendLog fails for some reason, this results for promise.all 
in finishTestItem
rejects with the reason of the first children promise that rejects

2018-06-20 13:02 UTC, lexecon requested changes
Copy the same code in the function inside the method, and use this function

2018-06-27 07:25 UTC, vadimromanyak commented
Retry Deepcode

2018-06-27 07:25 UTC, ghost commented
Failed to analyze this pull request. If you want to retry just tell me by creating a comment: "Retry Deepcode"

2018-06-27 08:44 UTC, vadimromanyak commented
@lexecon could you check the issue with deepcode? Does it relate to code changes?

2018-08-17 09:53 UTC, merged