EPMRPP-45141 - Update js client
reportportal/client-javascript pull request #44
Opened 2019-12-23 09:33 UTC by KatsiarynaTatarynovich

2020-01-14 08:29 UTC, DiscoElevator requested changes

2020-01-14 08:29 UTC, DiscoElevator commented on README.md
> +        tags: [
attributes

2020-01-14 08:29 UTC, DiscoElevator commented on spec/libSpec.js
>              merge_type: 'BASIC',
mergeType

2020-01-14 08:29 UTC, DiscoElevator commented on lib/report-portal-client.js
>              merge_type: "BASIC",
mergeType

2020-01-20 08:06 UTC, DiscoElevator commented on examples/testConnect.js
> +    endpoint: 'http://dev.epm-rpp.projects.epam.com:8080/api/v1',
Please revert to original value. Instance should not be exposed

2020-01-20 08:07 UTC, DiscoElevator commented on examples/testConnect.js
> +    token: '8275e0b8-7c6a-4edd-9ac8-87cd5831ce1b',
Please revert to original value. Token should not be exposed

2020-01-20 08:07 UTC, DiscoElevator commented on examples/testConnect.js
> +    launch: 'client_example',
The same as above

2020-01-20 08:07 UTC, DiscoElevator commented on examples/testConnect.js
> +    project: 'superadmin_personal',
The same as above

2020-01-20 08:19 UTC, DiscoElevator approved these changes

2020-01-20 10:14 UTC, AmsterGet approved these changes

2020-01-21 12:24 UTC, merged