update documentation, refactoring class RPClient, increase node version
reportportal/client-javascript pull request #5
Opened 2017-04-18 10:27 UTC by DmitryRomaniuk

2017-05-02 09:07 UTC, lexecon approved these changes

2017-05-02 09:10 UTC, lexecon reviewed
I checked only the syntax of the code

2017-05-03 09:09 UTC, dshlychkou commented on lib/client.js
> -                resolve(data);
Could please describe the purpose of this change?

2017-05-03 09:09 UTC, dshlychkou commented on lib/client.js
> +                    if (result instanceof Error) {
Could you please describe the purpose of this change?

2017-05-03 09:09 UTC, dshlychkou commented on lib/client.js
> +                    if (result instanceof Error) {
Could you please provide the purpose of this change?

2017-05-03 09:09 UTC, dshlychkou commented on lib/client.js
> +                        if (result instanceof Error) {
Could you please describe the purpose of this change?

2017-05-03 09:21 UTC, avarabyeu requested changes
Please, answer on Denis's questions

2017-05-04 21:23 UTC, closed without merging