EPMRPP-52034: [JS-CLIENT] Increase test coverage
reportportal/client-javascript pull request #75
Opened 2020-06-01 18:16 UTC by KatsiarynaTatarynovich

2020-06-02 13:00 UTC, ElenaRomanchuk requested changes
I suggest using `expectAsync(aPromise).toBeRejected();` to check if promise was rejected in all cases when it's possible.
Also, I think we should avoid checking correct/incorrect behavior by spying on the log (logDebug) function. It doesn't guarantee that functionality really works as we expect.

2020-06-02 13:00 UTC, ElenaRomanchuk commented on spec/report-portal-client.spec.js
> +        let client;
Why do you make variable `client` shared  between tests? It can affect each new test in describe. Is it necessary?

2020-06-02 13:00 UTC, ElenaRomanchuk commented on spec/report-portal-client.spec.js
> +    describe('now', () => {
I don't think that it's good idea to test `now` in this way. May be don't cover it at all?

2020-06-02 13:00 UTC, ElenaRomanchuk commented on spec/report-portal-client.spec.js
> +                expect(client.logDebug).toHaveBeenCalledWith('Found launches: id1');
I don't think we should test `logDebug` behavior

2020-06-02 13:00 UTC, ElenaRomanchuk commented on spec/report-portal-client.spec.js
> +            expect(promise.catch).toBeDefined();
Could we use `expectAsync(aPromise).toBeRejected();` to check this?

2020-06-02 13:00 UTC, ElenaRomanchuk commented on spec/report-portal-client.spec.js
> +            expect(client.logDebug).toHaveBeenCalledWith('Option isLaunchMergeRequired is false');
I suggest just check that client function wouldn't called by `not.toHaveBeenCalled()`.

2020-06-03 08:13 UTC, AmsterGet approved these changes

2020-06-03 08:53 UTC, ElenaRomanchuk approved these changes

2020-06-03 08:54 UTC, merged